namespace Unicorn.Utilities
{
    public class NameGenerator
    {
        /// <summary>
        /// Bộ random nickname
        /// </summary>
        public static string[] Names =
        {
            "Xemesis",
            "AnarchyAct",
            "ive",
            "Carter",
            "BULLET",
            "Plot",
            "Creeper",
            "Faker",
            "Tyler1",
            "FreZeeN",
            "Ervinne",
            "FanHart",
            "Gambitis",
            "HyperLand",
            "NoName",
            "SpaceShooter",
            "Juleedo",
            "Mediati",
            "Pulenced",
            "Ravixir",
            "ViruSs",
            "Misthy",
            "Scantand",
            "Shophood",
            "CDNThe3rd",
            "PewPew",
            "Imaqtpie",
            "ven",
            "Talentag",
            "404",
            "lace",
            "Daequan",
            "VampBee",
            "QTV",
            "MyNameIsSun",
            "HollowNight",
            "OneSoft",
            "Concept",
            "Contech",
            "Darthro",
            "DragonLou",
            "Br0",
            "Euroeh",
            "GameZone",
            "Floriab",
            "Hytext",
            "Voyboy",
            "Nozyme",
            "Olympine",
            "Rapca",
            "Revuldi",
            "SexyEats",
            "Error",
            "SlipScoop",
            "Smancy",
            "Snower",
            "TFBlade",
            "Tonedi",
            "Tyom",
            "Uber",
            "Weler",
            "Witecta",
            "Wittypy",
            "Yassuo",
            "Adhumust",
            "AprilLoves",
            "ArsenalFam",
            "Sneaky",
            "Shiphtur",
            "RocketStudio",
            "Celeste",
            "Hanst",
            "IdolRay",
            "Integen",
            "LexZero",
            "LogicScan",
            "KayPea",
            "PewDiePie",
            "Miracleas",
            "Natherde",
            "Duggie",
            "DrLupo",
            "Ninja",
            "Purest",
            "Schynth",
            "Slimed",
            "Spunkyly",
            "Sputence",
            "Wagamama",
            "Hacker",
            "TasticTren",
            "TickoEye",
            "Toothan",
            "Updatho",
            "Wetphyt",
            "Alloffi",
            "Abi",
            "SingSing",
            "ComfyPeak",
            "Critices",
            "Darise",
            "DressyPlea",
            "sant",
            "EdgyXan",
            "HungP0308",
            "GatoMagic",
            "HeadMarcs",
            "Husbard",
            "Falcon",
            "Ispost",
            "Jeansbu",
            "Keepupbo",
            "MaddStyx",
            "Mammyop",
            "Mediamsla",
            "pokémon",
            "Quickli",
            "Ramblid",
            "Scherli",
            "What",
            "IDK",
            "Dendi",
            "TaraUn",
            "Urat",
            "Virtuosoni",
            "Vowellsky",
            "ZapHott",
            "Rex",
            "IHas",
            "Asaurus Rex",
            "Uber",
            "Disguised",
            "OMG",
            "LOL",
            "LMAO",
            "Iam",
            "Milk",
            "MindOf",
            "Gamer",
            "The Gamer",
            "Dr",
            "Popper",
            "Big",
            "ItIsYe",
            "Boy",
            "Girl",
            "Person",
            "Captain",
            "Total",
            "The Dude",
            "The Gaming",
            "Gaming With",
            "Mr Game",
            "Ms Game"
        };

        public static string GetName()
        {
            return Names[UnityEngine.Random.Range(0, Names.Length)];
        }
    }

}